GET http://127.0.0.1:5000/movie/?director_id=2
Accept: application/json

###

DELETE http://127.0.0.1:5000/movie/2
Content-Type: application/json

###

PUT http://127.0.0.1:5000/movie/5
Content-Type: application/json

{
    "director_id": 5,
    "rating": 6.4,
    "year": 2010,
    "description": "Али - молодая амбициозная девушка из маленького городка с чудесным голосом, совсем недавно потеряла своих родителей. Теперь никому не нужная, она отправляется в большой город Лос-Анджелес, где устраивается на работу у Тесс, хозяйки ночного клуба «Бурлеск». За короткое время она находит друзей, поклонников и любовь всей своей жизни. Но может ли сказка длиться вечно? Ведь немало людей завидует этой прекрасной танцовщице...",
    "director": "Стив Энтин",
    "genre_id": 18,
    "genre": "Мюзикл",
    "title": "Бурлеск",
    "trailer": "https://www.youtube.com/watch?v=sgOhxneHkiE"
}

###

POST http://127.0.0.1:5000/movie/1
Content-Type: application/json

{
    "director_id": 5,
    "rating": 6.8,
    "year": 2011,
    "description": "зная девушка из маленького городка с чудесным голосом, совсем недавно потеряла своих родителей. Теперь никому не нужная, она отправляется в большой город Лос-Анджелес, где устраивается на работу у Тесс, хозяйки ночного клуба «Бурлеск». За короткое время она находит друзей, поклонников и любовь всей своей жизни. Но может ли сказка длиться вечно? Ведь немало людей завидует этой прекрасной танцовщице...",
    "director": "Стив Энтин",
    "genre_id": 18,
    "genre": "Мюзикл",
    "title": "Бурл",
    "trailer": "https://www.youtube.com/watch?v=sgOhxneHkiE"
}
